# 应用名称
spring:
  application:
   name: gateway
# 应用服务 WEB 访问端口
server:
  port: 8088
eureka:
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:8080/eureka
    fetch-registry: true
    register-with-eureka: true
  instance:
    hostname: localhost
zuul:
  routes:
    route1:
      path: /user/**
      serviceId: user
