# 应用名称
spring:
  application:
   name: gateway
# 应用服务 WEB 访问端口
server:
  port: 8088
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8080/eureka
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true
zuul:
  routes:
    route1:
      path: /user/**
      serviceId: user
management:
  health:
    redis:
      enabled: false
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always